[project]
name = "vrp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.3"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.2.6",
    "pulp>=3.2.2",
    "pyvroom>=1.14.0",
]
